---
name: "Build Firefox on macOS"
on:
  push:
    branches:
      - "**"
  workflow_run:
    workflows: ["Update Firefox version"]
    types:
      - completed
  pull_request:
    branches: [main]

jobs:
  check_evaluation:
    # The processor on this label is M1, not x86_64
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
      - run: nix build
